version: "3.9"
networks:
  keycloak:
    driver: "bridge"
  postgresql:
    driver: "bridge"
  auth:
    driver: "bridge"
  classes_ms:
    driver: "bridge"
volumes:
  keycloak-data:
    external: true
  postgresql-data:
    external: true
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - keycloak
  postgresql:
    container_name: postgresql
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=a12345678
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - postgresql
  auth:
    image: "auth:latest"
    depends_on:
      - "keycloak"
    links:
      - "keycloak"
    ports:
      - "8090:8090"
    environment:
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_CLIENT_ID=grupo7
      - KEYCLOAK_CLIENT_SECRET=HjTtaSOS39LaQ62HcUC1hZo6CC16q3f2
      - AUTH_SERVER_PORT=8090
    build: ./auth
    networks:
      - auth
  classes_ms:
    image: "classes-ms:latest"
    depends_on:
      - "auth"
      - "postgresql"
    links:
      - "auth"
      - "postgresql"
    ports:
      - "8087:8087"
    environment:
      - SERVER_PORT=8087
    build: ./classes-ms
    networks:
      - classes_ms