version: "3.9"
networks:
  constr-sw-2022-2:
volumes:
  keycloak-daata:
    external: true
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
    networks:
      - constr-sw-2022-2